// lib/questions.js

export const questions = [
  {
    id: 'businessType',
    question: 'What type of service do you offer?',
    type: 'select',
    options: [
      { value: 'website', label: 'Website/Blog' },
      { value: 'webapp', label: 'Web Application' },
      { value: 'mobileapp', label: 'Mobile App' },
      { value: 'ecommerce', label: 'E-commerce Store' },
      { value: 'saas', label: 'SaaS Platform' },
      { value: 'newsletter', label: 'Newsletter/Email Service' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'businessName',
    question: "What's your business/service name?",
    type: 'text',
    placeholder: 'Enter your business name',
  },
  {
    id: 'contactEmail',
    question: 'What email should users contact for privacy questions?',
    type: 'email',
    placeholder: 'privacy@yourcompany.com',
  },
  {
    id: 'dataCollection',
    question: 'What personal information do you collect?',
    type: 'multiselect',
    options: [
      { value: 'name', label: 'Name' },
      { value: 'email', label: 'Email address' },
      { value: 'phone', label: 'Phone number' },
      { value: 'address', label: 'Physical address' },
      { value: 'payment', label: 'Payment information' },
      { value: 'usage', label: 'Usage data/analytics' },
      { value: 'location', label: 'Location data' },
      { value: 'device', label: 'Device information' },
      { value: 'cookies', label: 'Cookies/tracking' },
    ],
  },
  {
    id: 'dataUse',
    question: 'How do you use this information?',
    type: 'multiselect',
    options: [
      { value: 'service', label: 'Provide the service' },
      { value: 'communication', label: 'Communicate with users' },
      { value: 'analytics', label: 'Analytics and improvements' },
      { value: 'marketing', label: 'Marketing communications' },
      { value: 'personalization', label: 'Personalize experience' },
      { value: 'security', label: 'Security and fraud prevention' },
      { value: 'legal', label: 'Legal compliance' },
    ],
  },
  {
    id: 'thirdPartySharing',
    question: 'Do you share data with third parties?',
    type: 'select',
    options: [
      { value: 'none', label: "No, we don't share data" },
      { value: 'service', label: 'Only with service providers' },
      { value: 'partners', label: 'With business partners' },
      { value: 'legal', label: 'Only when legally required' },
      { value: 'analytics', label: 'With analytics providers' },
    ],
  },
  {
    id: 'thirdPartyServices',
    question: 'Which third-party services do you use?',
    type: 'multiselect',
    condition: (answers) => answers.thirdPartySharing !== 'none',
    options: [
      { value: 'google-analytics', label: 'Google Analytics' },
      { value: 'stripe', label: 'Stripe (payments)' },
      { value: 'mailchimp', label: 'Mailchimp/Email service' },
      { value: 'aws', label: 'AWS/Cloud hosting' },
      { value: 'intercom', label: 'Intercom/Customer support' },
      { value: 'hotjar', label: 'Hotjar/Heatmaps' },
      { value: 'facebook', label: 'Facebook/Meta services' },
      { value: 'other', label: 'Other services' },
    ],
  },
  {
    id: 'dataRetention',
    question: 'How long do you keep user data?',
    type: 'select',
    options: [
      { value: 'account-active', label: 'While account is active' },
      { value: '1-year', label: '1 year after last activity' },
      { value: '2-years', label: '2 years after last activity' },
      { value: '3-years', label: '3 years after last activity' },
      { value: 'legal-minimum', label: 'Legal minimum required' },
      { value: 'indefinite', label: 'Indefinitely (with user consent)' },
    ],
  },
  {
    id: 'userRights',
    question: 'What rights do you give users over their data?',
    type: 'multiselect',
    options: [
      { value: 'access', label: 'Access their data' },
      { value: 'correct', label: 'Correct their data' },
      { value: 'delete', label: 'Delete their data' },
      { value: 'export', label: 'Export their data' },
      { value: 'opt-out', label: 'Opt out of marketing' },
      { value: 'restrict', label: 'Restrict processing' },
    ],
  },
];
